### ISSUE TITLE
merge problems

### ISSUE THREAD

**Issue by danielskatz** [ypriverol/os-proteomics#13]
After I made changes in https://github.com/ypriverol/os-proteomics/pull/11, including suggesting possibly adding me as an author (see https://github.com/ypriverol/os-proteomics/pull/11#issuecomment-2451966730), @bgruening suggested changes in https://github.com/ypriverol/os-proteomics/pull/12 (which were based on the state of the repo before my PR was merged) so that when it was merged, it removed my changes.

**Comment by ypriverol** [comment]
@danielskatz the current PR #15, addresses most of your comments. If you can give us feedback in the PR would be great. I will be doing a PR after that one, including a section about FAIR4RS after this one.

**Comment by danielskatz** [comment]
I can't this week. Maybe I can by the middle of next week.

**Comment by danielskatz** [comment]
Let's close this, as the change has been merged.
