### ISSUE TITLE
Add a section about the challenges of maintaining and sustaining OSS

### ISSUE THREAD

**Issue by wfondrie** [ypriverol/os-proteomics#27]
I think the manuscript at this point does a good job of highlighting the merits and benefits of OSS. However, we need to address the elephant in the room: the challenged of maintaining OSS.  This will be a critical part of the manuscript to acknowledge and potentially suggest solutions for the biggest reasons why folks do not build OSS.

This section should address:

- **Financial sustainability:** Although we touch on it throughout the manuscript, I don't think we do respect to the difficulty of continuously funding and OSS project. For example, the NIH funding model is not friendly to proposal seeking primarily to maintain existing software. As such, this may be a move folks into commercialization out of necessity.

- **Incentive structure:** The incentive structure for academia is in set against OSS is several way. There is to be gained in the way of publication or grants from OSS maintenance. Contributing to OSS owned by someone else often goes unrecognized as valuable. The constant push for publications grants naturally push folks to release new projects, rather than building upon previous ones in an effort enhance novelty.

- **Consistent maintainers:** In the academic setting, positions are often temporary and as such, it is difficult to have the consistent, long-term maintenance of an OSS project. Additionally, the creators of OSS routinely leave for unrelated industry positions or entirely different fields, leading to abandonware if there is no transition plan in place.

**Comment by ypriverol** [comment]
Hi @wfondrie I totally agree with it, Can you do a PR with this ideas?
