### ISSUE TITLE
Good news - AlfaFold 3 OSS

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/os-proteomics#28]
https://www.nature.com/articles/d41586-024-03708-4

**Comment by bgruening** [comment]
"Anyone can now download the AlphaFold3 software code and use it non-commercially. "

And the license is [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
CC have this to say about CC Software licenses: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by lazear** [comment]
CC BY-NC is not open source.

https://opensource.org/definition-annotated see point 6.
