### ISSUE TITLE
Make sure your name is in the author list 

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/os-proteomics#33]
@wenbostar , @maccoss @jke000 Can you add your names and affiliation to the author list? All authors that have contributed with comments, edits etc should be included.

**Comment by ypriverol** [comment]
thanks @maccoss !!!

**Comment by ypriverol** [comment]
Thanks @jke000

**Comment by percolator** [comment]
I added my orcid as well. Remove if it is not needed.

**Comment by ypriverol** [comment]
That is an excellent tip. I may need to search for all ORCID ids now.

**Comment by ypriverol** [comment]
PR here #44
