### ISSUE TITLE
Open for contribution

### ISSUE THREAD

**Issue by GeorgWa** [ypriverol/os-proteomics#34]
Dear all,

this is a really cool project and very close to my heart.
I only found out about the project recently and wanted to ask if you are still open to contributions?

Best,
Georg

**Comment by ypriverol** [comment]
Please feel free to jump in. Unfortunately, we only have 5 days more for contributions, but I guess that is plenty of time. I will be happy to review your PR ;). Please also feel free to send it to others in your lab.

**Comment by ypriverol** [comment]
I will close this issue now.
