### ISSUE TITLE
Analysis of licenses used in proteomics

### ISSUE THREAD

**Issue by bittremieux** [ypriverol/os-proteomics#8]
I scraped papers from PubMed published in JPR that mention a GitHub URL in the abstract (unfortunately it seems that even for OA papers the full text is not easily accessible) and calculated a few statistics. Sample size is 89 papers.

1. Many don't have a license. Otherwise various open-source licenses are used.

By definition unfortunately the majority of closed source software won't be included in this analysis because they won't list a GitHub URL in their papers.

![licenses](https://github.com/user-attachments/assets/8b6d6003-ed93-4775-8f1d-3c0fabbc2a33)

2. GitHub stars don't correlate with paper citations. Nor do the number of contributors.

![stars_vs_citations](https://github.com/user-attachments/assets/58c29366-f235-41f7-a910-3f76bbac0f9d)

Let me know if this is interesting and whether you can think of additional analyses.

**Comment by ypriverol** [comment]
@bittremieux is interesting. You can see that unspecific is a more "common" license.

**Comment by ypriverol** [comment]
This information has been already included in the manuscript.
